config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("elections/", include("elections.urls", namespace="elections")),
    path("users/", include("users.urls", namespace="users")),
    path('', include('promotion.urls')),
    path('', include('portfolio.urls')),
]

elections/urls.py
from django.urls import path
from . import views

app_name = "elections"

urlpatterns = [
    path("", views.ElectionListView.as_view(), name="elections"),
    path("<int:pk>/", views.ElectionDetailView.as_view(), name="detail"),
    path(
        "register/",
        views.ElectionRegisterView.as_view(),
        name="election-register",
    ),
    path("<int:pk>/certification/", views.CertificationView, name="certification"),
    path(
        "certification_for_agent/",
        views.CertificationAgentView,
        name="certification-for-agent",
    ),
    path("videorecord/", views.VideoRecord, name="video-record"),
    path("<int:pk>/vote/", views.VoteView.as_view(), name="vote"),
    path("<int:pk>/calculate/", views.Calculate, name="calculate"),
    path("<int:pk>/edit/", views.EditElectionView.as_view(), name="edit-election"),
    path("<int:pk>/delete/", views.deleteElection, name="delete-election"),
    path("<int:pk>/result/", views.ElectionResultView.as_view(), name="result"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("delete-user/", views.deleteUser, name="delete-user"),
]

elections/models.py
from django.db import models


class Election(models.Model):
    """Election Model Definition"""

    TYPE_PRESIDENT_ELELCTION = "president_election"
    TYPE_MAYOR_ELECTION = "mayor_election"
    TYPE_PARLIAMENTARY_ELECTION = "parliamentary_election"

    TYPE_CHOICES = (
        (TYPE_PRESIDENT_ELELCTION, "대통령 선거"),
        (TYPE_MAYOR_ELECTION, "시장 선거"),
        (TYPE_PARLIAMENTARY_ELECTION, "국회의원 선거"),
    )

    title = models.CharField(max_length=100)
    register_period_begin = models.DateTimeField(auto_now_add=False, null=True)
    register_period_end = models.DateTimeField(auto_now_add=False, null=True)
    election_period_begin = models.DateTimeField(auto_now_add=False, null=True)
    election_period_end = models.DateTimeField(auto_now_add=False, null=True)
    election_type = models.CharField(choices=TYPE_CHOICES, max_length=40, null=True)
    # election_area -> 라이브러리 사용해서 할지, 아니면 choice 사용해서 할지
    # candidate_list

    def __str__(self):
        return self.title

elections/forms.py
from django import forms
from django.forms import fields
from . import models
import elections


class ElectionRegisterForm(forms.ModelForm):
    class Meta:
        model = models.Election
        fields = [
            "title",
            "register_period_begin",
            "register_period_end",
            "election_period_begin",
            "election_period_end",
            "election_type",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"placeholder": "대한민국 제20대 대통령 선거"}),
            "register_period_begin": forms.DateTimeInput(
                attrs={"placeholder": "2020-01-01 09:00:00"}
            ),
            "register_period_end": forms.DateTimeInput(
                attrs={"placeholder": "2020-01-02 09:00:00"}
            ),
            "election_period_begin": forms.DateTimeInput(
                attrs={"placeholder": "2020-01-11 09:00:00"}
            ),
            "election_period_end": forms.DateTimeInput(
                attrs={"placeholder": "2020-01-12 09:00:00"}
            ),
        }

    def save(self, *args, **kargs):
        election = super().save(commit=False)
        election.save()

elections/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.decorators import gzip
from django.http import StreamingHttpResponse
import cv2
import threading
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import ListView, FormView, UpdateView
from django.urls import reverse_lazy, reverse
from django.views.generic.detail import DetailView

from django.db.models import Max
from . import forms, models

from promotion import models as promotions_model


class ElectionListView(ListView):

    """ElectionListView Definition"""

    model = models.Election
    paginate_by = 12
    paginate_orphans = 5
    context_object_name = "elections"


class ElectionDetailView(DetailView):

    """ElectionDetailView Definition"""

    model = models.Election
    template_name = "elections/election_detail.html"


class ElectionRegisterView(FormView):
    template_name = "elections/register.html"
    form_class = forms.ElectionRegisterForm
    success_url = reverse_lazy("elections:election-register")  # todo: 선거 리스트로 보내기

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class EditElectionView(UpdateView):

    model = models.Election
    template_name = "elections/edit-election.html"
    fields = (
        "title",
        "register_period_begin",
        "register_period_end",
        "election_period_begin",
        "election_period_end",
        "election_type",
    )
    success_url = reverse_lazy("elections:election-register")

    def get_object(self, queryset=None):
        # 지금 로그인 한 유저가 superuser가 아니면 404오류 띄우기
        election = super().get_object(queryset=queryset)
        if self.request.user.is_superuser == False:
            raise Http404()
        return election


def deleteElection(request, pk):
    if request.method == "POST":
        election = models.Election.objects.get(pk=pk)
        election.delete()
        return redirect("elections/register")


class ElectionResultView(DetailView):

    """ElectionResultView Definition"""

    def get(self, request, pk):
        try:
            election = models.Election.objects.get(pk=pk)
            promotions = promotions_model.Promotion.objects.filter(election=election.id)
            max_promotion = promotions.order_by("-vote_number").first()
     
        except models.Election.DoesNotExist:
            raise Http404()

        return render(
            request,
            "elections/election_result.html",
            {
                "election": election,
                "elected": "문재인",
                "candidates": promotions,
                "elected": max_promotion,
            },
        )


class VoteView(FormView):
    """
    Vote View
    """

    def get(self, request, pk):
        try:
            election = models.Election.objects.get(pk=pk)
            promotions = promotions_model.Promotion.objects.filter(election=election.id)
        except models.Election.DoesNotExist:
            raise Http404()
        return render(
            request,
            "elections/vote.html",
            {"election": election, "promotions": promotions},
        )


def Calculate(request, pk):
    election = models.Election.objects.get(pk=pk)
    promotions = promotions_model.Promotion.objects.filter(election=election.id)
    try:
        selected_choice = promotions.get(name_kor=request.POST["choice"])
    except (KeyError,):
        return render(
            request,
            "elections/vote.html",
            {"election": election, "promotions": promotions},
        )
    else:
        selected_choice.vote_number += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("elections:result", args=(election.id,)))


def CertificationView(request, pk):
    election = models.Election.objects.get(pk=pk)
    return render(request, "elections/certification.html", {"election": election})


def CertificationAgentView(request):
    context = {}
    return render(request, "elections/certification_forAgent.html", context)


class VideoCamera(object):
    def __init__(self):
        self.video = cv2.VideoCapture(0)
        (self.grabbed, self.frame) = self.video.read()
        threading.Thread(target=self.update, args=()).start()

    def __del__(self):
        self.video.release()

    def get_frame(self):
        image = self.frame
        _, jpeg = cv2.imencode(".jpg", image)
        return jpeg.tobytes()

    def update(self):
        while True:
            (self.grabbed, self.frame) = self.video.read()


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n\r\n")


@gzip.gzip_page
def VideoRecord(request):
    try:
        cam = VideoCamera()
        return StreamingHttpResponse(
            gen(cam), content_type="multipart/x-mixed-replace;boundary=frame"
        )
    except:  # This is bad! replace it with proper handling
        print("에러입니다...")
        pass

templates/elections/certification.html
{% extends "base.html" %}

{% block content %}

<h1>본인확인</h1>
<h1>Title: {{ election.title }}</h1>
<table>
    <tr>
        <td with="50%">
            <img src="http://127.0.0.1:8000/elections/videorecord/" style="width: 1000px;" />
        </td>

    </tr>
</table>
<a class="btn btn-default" href="{% url 'elections:vote' election.id %}">승인완료</a>
{% endblock content %}

templates/elections/certification_forAgent.html
{% extends "base.html" %}

{% block content %}

<h1>본인확인</h1>

<table>
    <tr>
        <td with="50%">
            <img src="http://127.0.0.1:8000/elections/videorecord/" style="width: 1000px;" />
        </td>

    </tr>

</table>
<button type="button" onclick="location.href='http://127.0.0.1:8000/elections/vote'">본인확인 완료</button>
{% endblock content %}

templates/elections/edit-election.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="w-full" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% if form.non_field.errors %}
        {% for error in form.non_field.errors %}
        <span class="text-warning font_medium text-md-center">{{error}}</span>
        {% endfor %}
        {% endif %}
        
        {% for field in form %}
        {% include "users/form_input.html" with field=field %}
        {% endfor %}
        
        <button class="btn bg-warning text-white">선거 수정</button>
    </form>
    <form method="POST" action="{% url 'elections:delete-election' election.id %}">
        {% csrf_token %}
        <button class="btn-error">선거 삭제</button>
    </form>
{% endblock content %}

templates/elections/election_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Title: {{ election.title }}</h1>

<p><strong>후보자 등록 기간 : </strong> {{ election.register_period_begin }} ~ {{ election.register_period_end}}</p>
<p><strong>선거 투표 기간 : </strong> {{ election.election_period_begin }} ~ {{ election.election_period_end }}</p>
<p><strong>선거 종류 :</strong> {{ election.election_type }}</p>
<a class="btn btn-default" href="{% url 'elections:certification' election.id %}">투표하기</a>
{% endblock content %}

templates/elections/election_form.html
<form method="POST" class="w-full" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field.errors %}
        {% for error in form.non_field.errors %}
            <span class="text-warning font_medium text-md-center">{{error}}</span>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        {% include "elections/form_input.html" with field=field %}
    {% endfor %}

    <button class="btn bg-warning text-white">{{cta}}</button>
</form>

templates/elections/election_list.html
{% extends "base.html" %}
{% block content %}
{% if object_list %}
<ul>
    <p>진행 중인 선거 목록</p>
    {% for election in object_list %}
    <li>
        <a href="{% url 'elections:detail' election.pk %}">{{ election.title }}</a>
        <a class="btn btn-default" href="{% url 'elections:result' election.id %}">투표 결과 확인하기</a>
        
    </li>
    {% endfor %}
</ul>
{% else %}
<p>선거 목록이 없습니다</p>
{% endif %}
{% endblock content %}

templates/elections/election_result.html
{% extends "base.html" %}
{% block content %}
<div>
<div style="background: black; color:white">
{{election.title}} 결과

</div>

{% if elected %}
    <div style=
        "
        margin-top: 50px;
        margin-left: 10px;
        font-weight: 600;
        font-size: 25px;
        text-align: left;
        "
    >당선을 축하합니다.
    </div>

    <div style="
            margin-top: 10px;
            text-align:center;
            width: 500px; 
            height: 50px;
            margin-bottom: 50px; 
            margin-left: 20px;
            font-weight: 600; 
            border: 1px solid; 
            border-radius: 15px;
            display: flex;"
        >
        <div style="margin:auto;">
        <span>{{elected.party}}</span> 
        <span>{{elected.candidate.first_name}} {{elected.candidate.last_name}} 후보</span>
        </div>
    </div>

    <div style=
        "
        margin-top: 50px;
        font-weight: 600;
        margin-left: 10px;
        font-size: 25px;

        "
    >전체 후보자 득표 정보</div>

        {% for candidate in candidates %} 
            
            <div style="margin-bottom: 30px; margin-top: 10px; margin-left: 20px;">
                <div> 기호: {{candidate.symbol}}번 </div>
                <div>소속정당: {{candidate.party}} </div>
                <div class="">이름: {{candidate.candidate.first_name}} {{candidate.candidate.last_name}} </div>

                <div class="">득표 수:{{candidate.vote_number}}표</div>
            </div>
        {% endfor %}
        {% else %}
        <div style="margin-top: 25px;"> 현재 후보자가 없어요.</div>
        {% endif %}
</div>

{% endblock content %}

templates/elections/form_input.html
<div class="input {% if field.errors %}has_error{% endif %}">
    {{field.label}}
    {{field}}
    {% if field.errors %}
        {% for error in field.errors %}
            <span>{{error}}</span>
        {% endfor %}
    {% endif %}
</div>

templates/elections/register.html
{% extends "base.html" %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
{% include "elections/election_form.html" with form=form cta="Register Election" %}
</div>
{% endblock content %}

templates/elections/vote-done.html
{% extends "base.html" %}

{% block content %}

<h3>투표가 성공적으로 처리 되었습니다</h3>
<br>
<a class="btn btn-default" href="{% url 'elections:elections' %}">선거 목록으로 돌아가기</a>
{% endblock content %}

templates/elections/vote.html
{% extends "base.html" %}

{% block content %}

<h1>{{election.title}}</h1>

<form action="{% url 'elections:calculate' election.id %}" method="post">
    {% csrf_token %}
    {% for promotion in promotions %}
    <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ promotion.name_kor}}">
    <label for="choice{{ forloop.counter }}">{{promotion.name_kor}}</label><br>
    <h1>{{promotion.symbol}}</h1>
    <h1>{{promotion.party}}</h1>
    {%endfor%}
    <input type="submit" value="Vote">
</form>
{% endblock content %}