config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("elections/", include("elections.urls", namespace="elections")),
    path("users/", include("users.urls", namespace="users")),
    path('', include('promotion.urls')),
    path('', include('portfolio.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("delete-user/", views.deleteUser, name="delete-user"),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    """Custom User Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "남자"),
        (GENDER_FEMALE, "여자"),
        (GENDER_OTHER, "그 외"),
    )

    MAIN_CITIES = (
        ("seoul", "서울특별시"),
        ("incheon", "인천광역시"),
        ("deagu", "대구광역시"),
        ("gwangju", "광주광역시"),
        ("deajeon", "대전광역시"),
        ("ulsan", "울산광역시"),
        ("sejong", "세종특별자치시"),
        ("busan", "부산광역시"),
        ("gyeonggi", "경기도"),
        ("kangwon", "강원도"),
        ("chungbuk", "충청북도"),
        ("cjungnam", "충청남도"),
        ("gyeongbuk", "경상북도"),
        ("gyeongnam", "경상남도"),
        ("jeonbuk", "전라북도"),
        ("jeonnam", "전라남도"),
        ("jeju", "제주특별자치도"),
    )

    # username & password
    resident_registration_number = models.CharField(
        max_length=14, blank=True, null=True
    )
    # 주민번호
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    main_city = models.CharField(
        choices=MAIN_CITIES, max_length=30, blank=True, null=True
    )
    sub_city = models.CharField(max_length=30, blank=True, null=True)
    # # 거주지

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = (
            "first_name",
            "last_name",
            "email",
            "resident_registration_number",
            "gender",
            "main_city",
            "sub_city",
        )
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Name"}),
            "sub_city": forms.Select(),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.shortcuts import render
from django.views.generic import FormView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login, logout
from . import forms, models


class LoginView(FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("elections:election-register")


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class UpdateProfileView(UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "resident_registration_number",
        "gender",
        "main_city",
        "sub_city",
    )
    success_url = reverse_lazy("elections:election-register")

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "First name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last name"}
        return form


def deleteUser(request):
    if request.method == "POST":
        user = request.user
        user.delete()
        return redirect("users:login")

templates/users/form_input.html
<div class="input {% if field.errors %}has_error{% endif %}">
    {{field.label}}
    {{field}}
    {% if field.errors %}
        {% for error in field.errors %}
            <span>{{error}}</span>
        {% endfor %}
    {% endif %}
</div>

templates/users/login.html
<form method="POST" class="w-full" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field.errors %}
        {% for error in form.non_field.errors %}
            <span class="text-warning font_medium text-md-center">{{error}}</span>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        {% include "users/form_input.html" with field=field %}
    {% endfor %}

    <button class="btn bg-warning text-white">login</button>
</form>

templates/users/signup.html
<form method="POST" class="w-full" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field.errors %}
        {% for error in form.non_field.errors %}
            <span class="text-warning font_medium text-md-center">{{error}}</span>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        {% include "users/form_input.html" with field=field %}
    {% endfor %}

    <button class="btn bg-warning text-white">sign up</button>
</form>

<script>
    const subCityData = {
        서울특별시: [
          "종로구",
          "중구",
          "용산구",
          "성동구",
          "광진구",
          "동대문구",
          "중랑구",
          "성북구",
          "강북구",
          "도봉구",
          "노원구",
          "은평구",
          "서대문구",
          "마포구",
          "양천구",
          "강서구",
          "구로구",
          "금천구",
          "영등포구",
          "동작구",
          "관악구",
          "서초구",
          "강남구",
          "송파구",
          "강동구"
        ],
    
        부산광역시: [
          "중구",
          "서구",
          "동구",
          "영도구",
          "부산진구",
          "동래구",
          "남구",
          "북구",
          "강서구",
          "해운대구",
          "사하구",
          "금정구",
          "연제구",
          "수영구",
          "사상구",
          "기장군"
        ],
        인천광역시: [
          "중구",
          "동구",
          "남구",
          "연수구",
          "남동구",
          "부평구",
          "계양구",
          "서구",
          "강화군",
          "옹진군"
        ],
        대구광역시: [
          "중구",
          "동구",
          "서구",
          "남구",
          "북구",
          "수성구",
          "달서구",
          "달성군"
        ],
        광주광역시: [
          "동구",
          "서구",
          "남구",
          "북구",
          "광산구"
        ],
        대전광역시: [
          "동구",
          "중구",
          "서구",
          "유성구",
          "대덕구"
        ],
      
        울산광역시: [
          "중구",
          "남구",
          "동구",
          "북구",
          "울주군"
        ],
    
        세종특별자치시: [],
    
        경기도: [
          "가평군",
          "고양시",
          "과천시",
          "광명시",
          "광주시",
          "구리시",
          "군포시",
          "김포시",
          "남양주시",
          "동두천시",
          "부천시",
          "성남시",
          "수원시",
          "시흥시",
          "안산시",
          "안성시",
          "안양시",
          "양주시",
          "양평군",
          "여주시",
          "연천군",
          "오산시",
          "용인시",
          "의왕시",
          "의정부시",
          "이천시",
          "파주시",
          "평택시",
          "포천시",
          "하남시",
          "화성시"
        ],
    
        강원도: [
          "원주시",
          "춘천시",
          "강릉시",
          "동해시",
          "속초시",
          "삼척시",
          "홍천군",
          "태백시",
          "철원군",
          "횡성군",
          "평창군",
          "영월군",
          "정선군",
          "인제군",
          "고성군",
          "양양군",
          "화천군",
          "양구군"
        ],
    
        충청북도: [
          "청주시",
          "충주시",
          "제천시",
          "보은군",
          "옥천군",
          "영동군",
          "증평군",
          "진천군",
          "괴산군",
          "음성군",
          "단양군"
        ],
      
        충청남도: [
          "천안시",
          "공주시",
          "보령시",
          "아산시",
          "서산시",
          "논산시",
          "계룡시",
          "당진시",
          "금산군",
          "부여군",
          "서천군",
          "청양군",
          "홍성군",
          "예산군",
          "태안군"
        ],
      
        경상북도: [
          "포항시",
          "경주시",
          "김천시",
          "안동시",
          "구미시",
          "영주시",
          "영천시",
          "상주시",
          "문경시",
          "경산시",
          "군위군",
          "의성군",
          "청송군",
          "영양군",
          "영덕군",
          "청도군",
          "고령군",
          "성주군",
          "칠곡군",
          "예천군",
          "봉화군",
          "울진군",
          "울릉군"
        ],
      
        경상남도: [
          "창원시",
          "김해시",
          "진주시",
          "양산시",
          "거제시",
          "통영시",
          "사천시",
          "밀양시",
          "함안군",
          "거창군",
          "창녕군",
          "고성군",
          "하동군",
          "합천군",
          "남해군",
          "함양군",
          "산청군",
          "의령군"
        ],
      
        전라북도: [
          "전주시",
          "익산시",
          "군산시",
          "정읍시",
          "완주군",
          "김제시",
          "남원시",
          "고창군",
          "부안군",
          "임실군",
          "순창군",
          "진안군",
          "장수군",
          "무주군"
        ],
      
        전라남도: [
          "여수시",
          "순천시",
          "목포시",
          "광양시",
          "나주시",
          "무안군",
          "해남군",
          "고흥군",
          "화순군",
          "영암군",
          "영광군",
          "완도군",
          "담양군",
          "장성군",
          "보성군",
          "신안군",
          "장흥군",
          "강진군",
          "함평군",
          "진도군",
          "곡성군",
          "구례군"
        ],
      
        제주특별자치도: [
          "제주시",
          "서귀포시"
        ]
      }
    
    var mainCity = document.getElementById("id_main_city");
    console.log(mainCity);

    mainCity.onchange = function () {
        var subCity = document.getElementById("id_sub_city");
        var mainOption = mainCity.options[mainCity.selectedIndex].innerText;
        const subOption = subCityData[mainOption];
        subCity.length = 0;
        for(var i = 0; i < subOption.length; i++) {
            var option = document.createElement('option');
            option.innerText = subOption[i];
            subCity.append(option);
        }
    }

</script>

templates/users/update-profile.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="w-full" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% if form.non_field.errors %}
        {% for error in form.non_field.errors %}
        <span class="text-warning font_medium text-md-center">{{error}}</span>
        {% endfor %}
        {% endif %}
        
        {% for field in form %}
        {% include "users/form_input.html" with field=field %}
        {% endfor %}
        
        <button class="btn bg-warning text-white">update profile</button>
    </form>
    <form method="POST" action="{% url 'users:delete-user'%}">
        {% csrf_token %}
        <button class="btn-warning">회원탈퇴</button>
    </form>
{% endblock content %}